with ENROLLMENTS as (

   select * from {{ source('ACADEMIC_INFORMATION_SYSTEM','ENROLLMENTS') }}

),

DIM_DEPARTMENT as (

    select * from {{ ref('DIM_DEPARTMENT') }}

),

DIM_STUDENT as (
    select * from {{ ref('DIM_STUDENT') }}
),

DIM_COURSE as (

    select * from {{ ref('DIM_COURSE') }}

),

DIM_ADMISSION as (

    select * from {{ ref('DIM_ADMISSION') }}

),
	 
final as (
            select E.ENROLLMENT_ID,E.ENROLLMENTDATE,E.ENROLLMENTACTIVE,E.ENROLLMENTSTATUS,E.GRADE,E.COURSESTARTDATE,
E.TERM,S.STUDENT_ID,D.DEPARTMENT_ID,C.COURSE_ID ,C.CREDITS ,A.ADMISSION_ID 
from ENROLLMENTS E
INNER JOIN DIM_COURSE C on E.COURSE_ID = C.COURSE_ID
INNER JOIN DIM_ADMISSION A ON E.STUDENT_ID = A.STUDENT_ID 
INNER JOIN DIM_STUDENT S on E.STUDENT_ID = S.STUDENT_ID
INNER JOIN DIM_DEPARTMENT D on S.DEPARTMENT_ID = D.DEPARTMENT_ID

)

select * from final


